import "./globals.css"
import "@worldcoin/mini-apps-ui-kit-react/styles.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import MiniKitProvider from "@/components/minikit-provider"
import dynamic from "next/dynamic"
import AuthProvider from "@/components/auth-provider"

const inter = Inter({ subsets: [] })

export const metadata: Metadata = {
  title: "Relist - Sell used, earn.",
  description: "Generated by create next app",
}

const ErudaProvider = dynamic(
  () => import("../components/Eruda").then((c) => c.ErudaProvider),
  {
    ssr: false,
  }
)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ErudaProvider>
            <MiniKitProvider>{children}</MiniKitProvider>
          </ErudaProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
